#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 1024) in;
layout(set = 0, binding = 0) readonly buffer InputBuffer  { uint data[]; } inputData;
layout(set = 0, binding = 1)          buffer OutputBuffer { uint data[]; } outputData;

void main() {
    // grab global ID
	uint gID = gl_GlobalInvocationID.x;

    // do math
    outputData.data[gID] = inputData.data[gID] * 2 + 1;
}
