#ifndef SLIM_EXAMPLE_CONFIG_H
#define SLIM_EXAMPLE_CONFIG_H

#define GLM_FORCE_DEPTH_ZERO_TO_ONE

#define ENABLE_GBUFFER_VISUALIZATION
#define ENABLE_OBJECT_VISUALIZATION
#define ENABLE_SURFEL_GRID_VISUALIZATION
#define ENABLE_SURFEL_DEBUG_VISUALIZATION
#define ENABLE_SURFEL_COVERAGE_VISUALIZATION
#define ENABLE_SURFEL_BUDGET_VISUALIZATION
#define ENABLE_SURFEL_VARIANCE_VISUALIZATION
#define ENABLE_SURFEL_DEPTH_VISUALIZATION
#define ENABLE_MINUSCALE_SCENE

// #define ENABLE_SPONZA_SCENE
#define ENABLE_COLOR_BLEEDING_SCENE

// #define ENABLE_GAMMA_CORRECT
// #define ENABLE_DIRECT_ILLUMINATION
#define ENABLE_SURFEL_RADIAL_DEPTH
#define ENABLE_GBUFFER_WORLD_POSITION

#endif // SLIM_EXAMPLE_CONFIG_H
