#ifndef SLIM_EXAMPLE_CONFIG_H
#define SLIM_EXAMPLE_CONFIG_H

#define GLM_FORCE_DEPTH_ZERO_TO_ONE

#define ENABLE_GBUFFER_VISUALIZATION
#define ENABLE_OBJECT_VISUALIZATION
#define ENABLE_GRID_VISUALIZATION
#define ENABLE_COVERAGE_VISUALIZATION
#define ENABLE_SURFEL_BUDGET_VISUALIZATION
#define ENABLE_MINUSCALE_SCENE

#endif // SLIM_EXAMPLE_CONFIG_H
