#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 256) in;
layout(set = 0, binding = 1) readonly buffer InputBuffer  { uint data[]; } sourceData;
layout(set = 0, binding = 2)          buffer OutputBuffer { uint data[]; } outputData;

void main() {
    // grab global ID
	uint gID = gl_GlobalInvocationID.x;

    // do math
    outputData.data[gID] = sourceData.data[gID] * 2 + 1;
}
